### ISSUE TITLE
Images - Global

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/dp-420-cosmos-db-dev.ja-JP#1]
Please add LOC-images into folder: \instructions\media\

**Comment by stonezy123** [comment]
The locfile status is InLocalization, waiting for check In. [ICMS QUERY](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=C%26E&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5GYWxzZTwvU0hSUD48U0FUTz5GYWxzZTwvU0FUTz48U0FMTz5UcnVlPC9TQUxPPjxRRT4%2bMjwvUUU%2bPFFUPj48UVIgSWQ9IjEiIENQSUQ9IjAiPkN1cnJlbnQ7RmlsZXM7SG9zdCBDb250ZW50IFN0b3JlO0VxdWFsO0xBQl9kcC00MjA8L1FSPjxRUiBJZD0iMiIgQ1BJRD0iMCI%2bYW5kO0N1cnJlbnQ7TG9jRmlsZXM7TGFuZ3VhZ2U7RXF1YWw7SmFwYW5lc2UgKEphcGFuKTwvUVI%2bPFFSIElkPSIzIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtGaWxlcztIb3N0IEZpbGUgUmVmZXJlbmNlO0NvbnRhaW5zOy9pbnN0cnVjdGlvbnMvbWVkaWEvPC9RUj48L1FUPjxSRz48R0M%2bTlVMTDwvR0M%2bPC9SRz48L1ZQUT4%3d).
