### ISSUE TITLE
Missing About

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/dp-420-cosmos-db-dev.ja-JP#18]
Missing the information in "About" field.

Missing the Link to "Github Pages"
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/64255878/157818427-6f72d0ab-45a4-4f2e-8981-a9619d19c410.png)

**Comment by stonezy123** [comment]
not loclization issue

**Comment by olprod** [comment]
![image](https://user-images.githubusercontent.com/16075726/184617932-5ee19dd4-84f8-4bbc-854f-bc08245fd22c.png)
