### ISSUE TITLE
Global links

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/dp-420-cosmos-db-dev.ja-JP#19]
https://github.com/microsoftlearning/dp-420-cosmos-db-dev

Replace by:

https://github.com/microsoftlearning/dp-420-cosmos-db-dev.ja-JP

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team
