### ISSUE TITLE
readme.md

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/dp-420-cosmos-db-dev.ja-JP#20]
Current Translation:
https://microsoftlearning.github.io/MCT-User-Guide/

Suggested Translation:
https://microsoftlearning.github.io/MCT-User-Guide-JA/

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team
