### ISSUE TITLE
Module translations

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/dp-420-cosmos-db-dev.ja-JP#21]
Few, if any, of the 'Module' sections at the top of these .md Instructions files has the Module title translated.  Most localized repos do this, is it planned to be done to this (and any other DP-420) localized repo?

![image](https://user-images.githubusercontent.com/49700217/174487869-9281cc70-b70c-424c-a1e7-88f755074f1d.png)

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
please help provide locfile path. thanks
